### ISSUE TITLE
StubbleException: You have reached the maximum recursion limit of 256.

### ISSUE THREAD

**Issue by badstorm** [StubbleOrg/Stubble#10]
I have a UWP project that use Stubble to render some mustache file. Some time I'll get this exception: 
`You have reached the maximum recursion limit of 256.`
What does it means?

Thanks

**Comment by Romanx** [comment]
Hi there,

That means your template is most likely recursive or you have a very deep structure that you're trying to render. If you know your structure is very deep you can increase the limit this is done by using the StubbleBuilder to update the property calling `SetMaxRecursionDepth`. This can't be done on the `StaticStubbleRenderer`.

If you don't think it's your data then it could be your template, feel free to post it here and I'll try help.

Thanks,

**Comment by Romanx** [comment]
@badstorm did you have any luck with your problem?

**Comment by Romanx** [comment]
@badstorm I've rewritten our parsing and rendering system for Alpha 16. This should solve any of the odd edges with regards to recursive template. I'm going to close this but feel free to post back if you find you're having any issues.
