### ISSUE TITLE
I Need to set QR code by base64

### ISSUE THREAD

**Issue by drinkmuffin** [StubbleOrg/Stubble#104]
HI

my html like this

 <img src='{{qrCodeSrc}}' />

qrCodeSrc set 'data:image/png;base64,...........'

but the result will be "<img>" src is empty

what need i do?

**Comment by Romanx** [comment]
Hi there,

I'm not sure I can work out what is wrong from your sample. Can you provide a some reproduction code?

Thanks,

**Comment by drinkmuffin** [comment]
this template is 
"&lt;!DOCTYPE html&gt;&lt;html&gt;&lt;head&gt;&lt;meta charset=&quot;utf-8&quot; /&gt;&lt;title&gt;&lt;/title&gt;&lt;/head&gt;&lt;body&gt;&lt;div&gt;&lt;img src=&quot;{{qrCodeSrc}}&quot; /&gt;&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;"

the qrCodeSrc = "'data:image/png;base64,...........'"

after result will be "&lt;img&gt;&lt;/img&gt;"

i hope the image display by data-url(base64)

**Comment by Romanx** [comment]
Hi there,

Your example looks like it should work fine. Your code should look something like this

```csharp
var stubble = new StubbleBuilder().Build();
var template = "<!DOCTYPE html><html><head><meta charset="utf-8" /><title></title></head><body><div><img src="{{qrCodeSrc}}" /></div></body></html>";

var output  = stubble.Render(template, new {
    qrCodeSrc = "data:image/png;base64,..........."
});
```

**Comment by Romanx** [comment]
I'm going to close this due to inactivity, hopefully the example helped.
