### ISSUE TITLE
Not compatible with .Net standard 2.1 and .Net Core 3.1

### ISSUE THREAD

**Issue by pratik-cognologix** [StubbleOrg/Stubble#119]
Getting this issue with .Net Standard 2.1 and .Net Core 3.1

Could not load file or assembly 'Stubble.Core, Version=1.9.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.","exception":"System.IO.FileNotFoundException: Could not load file or assembly 'Stubble.Core, Version=1.9.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.\r\nFile name: 'Stubble.Core, Version=1.9.0.0, Culture=neutral, PublicKeyToken=null'\r\n

**Comment by sjd2021** [comment]
I'm actually very confused by this. This library has millions of downloads, and stubble seems to be very much supported. But I can't find any libraries which are up-to-date for it which makes me lean towards liquid templates which are less user friendly and require more code.. @pratik-cognologix  @amithegde could you point those of us on .NET Core 3.1 - .NET 6 in a general direction for some guidance?

**Comment by sjd2021** [comment]
@pratik-cognologix  @Romanx Do you have any idea what we should be doing for those of us on .NET Core 3.1 - NET 6? 
Mustache support seems to be very much alive, but there are no recently available nuget packages that I can find for it, so I'm leaning towards liquid templates because there are libraries like fluid which support this. Is mustache actually dying out? I prefer it to liquid because the templates have less code in them and are easier to build HTML WYSIWYG around IMO.

**Comment by pratik-cognologix** [comment]
@sjd2021 Thank you for suggesting me another good template engine was looking for long time that is live today :)  Actually my concern is the same, is mustache dying out, no recent updates and nuget packages available. Closing this thread.

Thank you @sjd2021 .

**Comment by Romanx** [comment]
Hey there,

Stubble should work on netcore and netstandard and we'd love to fix it if it doesn't somehow and unfortunately your exception doesn't give enough information. If you have a repro I'd love to see it.

As for mustache, it as a templating language is effectively _finished_ this is to say it won't be changing and adding features. So if it supports what you need from a templating language then it works great.

If you need what a language like liquid provides then that may be a good fit. I'd also recommend Scriban if looking at alternatives.
