### ISSUE TITLE
Parent nested object access

### ISSUE THREAD

**Issue by phspies** [StubbleOrg/Stubble#122]
I'm trying to access a parent nested value from a child loop. I tried a couple of combinations, but cannot get this to work.

```
{{#operations}}
{{#operation.parameters}}
{{operations.current.name}} {{operations.parameters.current.name}}
{{#/operation.parameters}}
{{#/operations}}
```

**Comment by Romanx** [comment]
Hey i'm going to close this due to inactivity, feel free to open a new issue with a minimal reproduction if you're still having issues.
