### ISSUE TITLE
Vue-email-editor relies on external iframe source, problematic for intranet environments

### ISSUE THREAD

**Issue by phoben** [StubbleOrg/Stubble#147]
Hello,

I have been using the vue-email-editor component and noticed that it runs within an iframe:

`<iframe src="http://editor.unlayer.com/1.9.2/editor.html" frameborder="0" width="100%" height="100%" style="min-width: 1024px; min-height: 100%; height: 100%; width: 100%; border: 0px;"></iframe>`

My project is running on an internal network server without access to the external internet.

My question is: under these circumstances, would the vue-email-editor be unusable since it requires access to an external source (http://editor.unlayer.com/)? If so, is there an alternative method or workaround to utilize vue-email-editor on an intranet server?

Thank you for your assistance.

**Comment by Romanx** [comment]
Hi, think you might have put this issue on the wrong repository. We have no interaction with `vue-email-editor`
