### ISSUE TITLE
empty Dictionary will yield "System.Collections..."

### ISSUE THREAD

**Issue by schmitch** [StubbleOrg/Stubble#17]
Hello, I'm not sure if this is a bug, but if I do:

```csharp
            Dictionary<string, object> dataHash = new Dictionary<string, object>();
            var output = StaticStubbleRenderer.Render("{{Foo.Value}}", dataHash);
            Console.WriteLine(output);
```
it will print `System.Collections.Generic.Dictionary`2[System.String,System.Object]`
I can also set Foo to null and it will still give me that message, wouldn't it be better to just show nothing or return a empty string?  actually this will happen as soon as I only use `{{ foo }}`. if foo is not defined it will just return a empty string.

At the moment I can override the behaviour by registering a custom `AddValueGetter`:

```csharp
RendererSettings rsb = new RendererSettingsBuilder().AddValueGetter(typeof(IDictionary<string, object>), (o, s) =>
            {
                if (o is IDictionary<string, object>) // this might be unnecessary
                {
                    var oo = o as IDictionary<string, object>;
                    if (oo.ContainsKey(s))
                    {
                        return oo[s];
                    }
                }
                return ""; // the problem might be that the default implementation emits null, which will yield the Dictionary message
               
            }).BuildSettings();
```

**Comment by Romanx** [comment]
Hi there,

Looking at your first example it shouldn't return anything since the value `Foo` shouldn't exist in the data hash, it'll look for the key, find no result and then render an empty string. 

Could you provide a simple reproduction case so that I can run it in a test and also the version of stubble you're currently running? There have been some breaking changes in the last few alpha releases.

**Comment by schmitch** [comment]
Actually running:
```
Dictionary<string, object> dataHash = new Dictionary<string, object>();
var output = StaticStubbleRenderer.Render("{{Foo.Value}}", dataHash);
```
should return an empty string.
But it yields `System.Collections.Generic.Dictionary\`2[System.String,System.Object]`. Sadly I'm not to familiar with xUnit.

**Comment by Romanx** [comment]
@schmitch that sounds like a bug then. Let me take a look later on today and see if I can reproduce the issue.

**Comment by Romanx** [comment]
@schmitch You were entirely right and this was a bug with looking up nested values from a context. I've added some tests around it and found a related issue in that nested lookups weren't throwing when they should be when a flag was set.

I've just made a new release, Alpha 17 containing the changes which should appear on Nuget soon and fix your problems. Please feel free to open another issue if you experience any other issues 👍
