### ISSUE TITLE
Update the "How to use" section and put it in the docs

### ISSUE THREAD

**Issue by DavidRouyer** [StubbleOrg/Stubble#19]
The "How to use" section is not up to date.

The example:
```
var stubble = new Stubble();
var myObj = new MyObj();
using (StreamReader streamReader = new StreamReader(".\Path\To\My\File.Mustache", Encoding.UTF8))
{
    var output = stubble.Render(streamReader.ReadToEnd(), myObj);
}
```

should be:
```
var stubble = new StubbleBuilder().Build();
var myObj = new MyObj();
using (StreamReader streamReader = new StreamReader(".\Path\To\My\File.Mustache", Encoding.UTF8))
{
    var output = await stubble.RenderAsync(streamReader.ReadToEnd(), myObj);
}
```

**Comment by Baccanno** [comment]
Hi Romanx,
We've been using Nustach for a while now, though we're getting issues with it. (lately, nesting context not working for instance, a simple test with {{Data.Value}} works but {{#Data}}{{Value}}{{/Data}} is empty... with { Data : { Value : "MyValue" }}, though it should as specified in "Non-False Values" mustache specification )
We're more keen on mustache blunt specification anyway and we're waiting for a beta build of Stubble for at least 1 year.
Though we'll need API to be quite stable. How far are you from this point and having a documentation ?

Best,

**Comment by freerider7777** [comment]
How is a new release going? :)

**Comment by Romanx** [comment]
Hey @freerider7777 I'm actually just polishing up some performance work along with compiling templates which will bring my feature compatibility with Nustache as 1-to-1. You can see the work on the feature/compilation branch. Hoping to get a new alpha out this weekend with a look at a beta shortly after that. 

Any feedback after the release will be more than welcomed!

**Comment by x4dr** [comment]
https://github.com/StubbleOrg/Stubble/wiki
still does not reflect this. 
i needed to come here and read the should be part of a closed issue to actually begin using stubble at all

**Comment by Romanx** [comment]
@x4dr Really sorry for the trouble that you ran into. I'll update the wiki today to redirect to the how-to docs. 

Thanks for posting here and letting me know.
