### ISSUE TITLE
Emtpy lines are renderer for non-existing tags and sections

### ISSUE THREAD

**Issue by Elringus** [StubbleOrg/Stubble#24]
```
using Stubble.Core.Builders;
using System;

class Program
{
    static string template = 
@"Lorem ipsum dolor sit amet, consectetur adipiscing elit.
{{{ATag}}}
{{{ATag}}}
{{{ATag}}}
{{{ATag}}}
Nulla non nulla sit amet ligula fringilla gravida sed vitae felis.
{{#ASection}}Aenean eu dui tincidunt risus fringilla fringilla.{{/ASection}}
{{#ASection}}Aenean eu dui tincidunt risus fringilla fringilla.{{/ASection}}
{{#ASection}}Aenean eu dui tincidunt risus fringilla fringilla.{{/ASection}}
{{#ASection}}Aenean eu dui tincidunt risus fringilla fringilla.{{/ASection}}
Nulla nisl nulla, vulputate quis dui eget, sagittis placerat neque. Aliquam eu arcu eget elit semper dapibus.";

    static void Main (string[] args)
    {
        var stubble = new StubbleBuilder().Build();
        var document = stubble.Render(template, null);
        Console.Write(document);
        Console.ReadKey();
    }
}
```

Will render following:
![](https://i.gyazo.com/53391d37e2f6482e3b1b934960ff0ccf.png)

Expected result:
![](https://i.gyazo.com/b1a6e1be079ace07fa3938f6a2fb4f24.png)

**Comment by Romanx** [comment]
Hi there,

I've just taken a look at this with regards to the mustache spec and from what I can see we're doing the "correct" thing which is semantically the lines go `\n{{Tag}}\n` so when the tag is empty it becomes `\n\n` causing the empty lines. I've checked the implementation of mustache.js in the [codepen here](https://codepen.io/anon/pen/rKqbPa?editors=1111) which seems to do the same.

While I don't think i'd be happy with making it default functionality, i've been considering adding hooks at certain points in the rendering pipeline such as:
- Pre-Parsing
- Post-Parsing
- Pre-Rendering
- Post-Rendering

This would allow you to add a handler on Post-Processing to remove any empty newlines in the renderer allowing you to keep your code dry. I probably won't target this for the 1.0 release however.

Would this solution be good for you? Without knowing your use case it's the best I can suggest, perhaps for now post-processing your string to remove blank lines

**Comment by Elringus** [comment]
Hi, Thank you for looking into that! The solution with post-rendering hooks will work, I think. My case is about rendering multiple shader code (CG) variants based on single mustache template. There are a lot of places in the templates, where some tags or sections should not be rendered in some variants and the resulting documents are starting to look a bit... holey :) It's not critical in any way, actually. So in case this feature doens't really fit the design, I think I can live with this.

**Comment by Romanx** [comment]
Hey there, we're thinking of implementing the proposed solution of adding hooks into the pipeline and the issue tracking that is #66.

Please feel free to leave any feedback or suggestions on that issue and i'm going to close this in the meantime.

Thanks very much for using the library
