### ISSUE TITLE
How support dynamic type in view value

### ISSUE THREAD

**Issue by cipchk** [StubbleOrg/Stubble#30]
the example code:

```cs
var data = JsonConvert.DeserializeObject("{ \"name\": \"test\" }");
var tpl = "My name is: {{name}}";

var stubble = new StubbleBuilder().Build();
var res = stubble.Render(tpl, data);
```

I expected value:

```html
My name is: test
```

But just only: 

```html
My name is: 
```

**Comment by Romanx** [comment]
Hi @cipchk,

JObjects are a special case of dynamic which is handled separately from the main library. If you install the [Stubble.Extensions.JsonNet](https://github.com/StubbleOrg/Stubble.Extensions.JsonNet) library then that should work with only a minor change to the builder.

Let me know if you have any other questions.

**Comment by cipchk** [comment]
Hi @Romanx,

I solved the problem via Stubble.Extensions.JsonNet, thank you very much about your work.
