### ISSUE TITLE
ValueGetters and EnumerationConverters for CompilationRenderer

### ISSUE THREAD

**Issue by yufeih** [StubbleOrg/Stubble#32]
Here is currently no way to set `ValueGetters in `CompilerSettingsBuilder`, it is missing `AddValueGetter` and `AddEnumerationConverters`.

**Comment by Romanx** [comment]
Hi there,

That's a massive oversight and is definitely supposed to be there. Thanks for reporting it. 

It looks like the enumeration converters aren't wired up at all so i'll look at why there were dropped for 1.0 and add them back.
