### ISSUE TITLE
Add Cake plugin

### ISSUE THREAD

**Issue by gtbuchanan** [StubbleOrg/Stubble#37]
It would be great to easily use Mustache in Cake scripts. I propose creating a Cake.Stubble plugin with some signatures like:

```
string MustacheRender(string template, object viewModel);

string MustacheRender(string template, object viewModel, Action<RendererSettingsBuilder> configurator);

string MustacheRenderFile(FilePath templateFile, object viewModel);

string MustacheRenderFile(FilePath templateFile, object viewModel, Action<RendererSettingsBuilder> configurator);
```

The Cake team [discussed](https://github.com/cake-build/cake/issues/124) adding templating support to Cake at one point, but I think it fell through.

**Comment by Romanx** [comment]
Hi there,

I'd actually thought about doing this recently since i've actually written a Cake plugin already [Cake.Coverlet](https://github.com/romanx/cake.coverlet).

I'll add the enhancement tag to this but I will likely open another repository if I do this.

Thanks,
