### ISSUE TITLE
Can I use one StubbleVisitorRenderer instance per application instance?

### ISSUE THREAD

**Issue by alperenbelgic** [StubbleOrg/Stubble#40]
Hi, 
Thank you for this great library you provide. 
I have a question about its usage. 
Is it safe to use RenderAsync method of a StubbleVisitorRenderer instance in parallel with different parameters? 
I am planning to provide it in a service wrapper which will have one instance at a time via Unity. 
Thank you,

**Comment by Romanx** [comment]
Hi there,

The renderer should be thread safe as we've taken as many precautions as we know to make it so. Please let us know if you run into any issues but I have used it in DI as a singleton instance, in an API having many requests at once without an issue.

Thanks,

**Comment by Romanx** [comment]
ques
