### ISSUE TITLE
Add render function overload for Lambdas

### ISSUE THREAD

**Issue by Baccanno** [StubbleOrg/Stubble#46]
[EDIT] 
I'm looking at SectionTokenRenderer and I can't see any lambdas that would hand the current context.
What could be handy is that a rendering function is passed to the lambdas like in mustache.js

Not sure about the code, but it's the idea.

```c#
//line SectionTokenRenderer:51
     else if (value is Func<dynamic, string, object> || value is Func<string, object>)
            {
                var functionDynamicValue = value as Func<dynamic, string, object>;
                var functionStringValue = value as Func<string, object>;
                var sectionContent = obj.SectionContent;

                value = functionDynamicValue != null
                    ? functionDynamicValue.Invoke(context.View, sectionContent.ToString())
                    : functionStringValue.Invoke(sectionContent.ToString());

                renderer.Render(context.RendererSettings.Parser.Parse(value.ToString(), obj.Tags), context);
            }
```

```c#
//additionnal function type
value is Func<dynamic, string, Action<string>, object>

var functionDynamicValueWithContext  = value as Func<dynamic, string, Action<string>, object>

value = functionDynamicValue.Invoke(context.View, sectionContent.ToString(), toRender => RENDER_FUNC_WITH_CONTEXT

```

Usage : 
```c#
object MyLambda( dynamic data, string text, Action<string> renderer)
{
 return renderer( "{{{"  + renderer( data.Far.Boo ) + "}}}" );
}
```

[ORIGINAL] 
Hi I'm comming from Nustache, and mainly I want to swap to Stubble because it is maintained and closer to Mustache Specs. I used to work with mustache.js for 2 years prior to going to c# world and I can't find the correct lib to get what I was doing with lambdas.

Now my setup is already working quite well with nustache but for one thing. I can't get the context to apply on Lambda functions :

### A. The Ugly I did with nustache (you can pass it all, it will give you the .. context)
I create an instance scoped object that will then be utilized by the lambdas, so I can get access recursively to my data object and lambdas when for instance doing recursive templating.
```c#
            _data = new Dictionary<string, object>
            {
                { "Dy", (Lambda) DyLambda }, // this is used in example
                { "Rec", (Lambda) RecLambda },
                { "SkBase", (Lambda) SkBaseLambda },
                { "Sk", (Lambda) SkLambda },
                { "SkCol", (Lambda) SkColLambda },
                { "SkDesc", (Lambda) SkDescLambda },
                { "Math", (Lambda) MathLambda },
                { "Readable", (Lambda) ReadableLambda },
                { "Lang", LangSerializable },
                { "Data", data }
            };


        private object DyLambda(string content, RenderContext context, RenderFunc writer)
        {
            return Render.StringToString("{{{" + RenderWithPartial(content, GetDataFromCtx(context)) + "}}}",
                GetDataFromCtx(context), PartialResolver);
        }


        public string RenderWithPartial(string content, object data, RenderContextBehaviour context = null)
        {
            return Render.StringToString(content, data, PartialResolver, context);
        }

        private object GetDataFromCtx(RenderContext context)
        {
            return new Dictionary<string, object>
            {
                { "Dy", (Lambda) DyLambda },
                { "Rec", (Lambda) RecLambda },
                { "Readable", (Lambda) ReadableLambda },
                { "SkBase", (Lambda) SkBaseLambda },
                { "Sk", (Lambda) SkLambda },
                { "SkCol", (Lambda) SkColLambda },
                { "SkDesc", (Lambda) SkDescLambda },
                { "Lang", LangSerializable },
                { "Data", context.GetValue("Data") },
                { "Skill", context.GetValue("Skill") },
                { "Skills", context.GetValue("Skills") },
                { "Math", (Lambda) MathLambda }
            };
        }
```

But then I can't consistently get the context of my data :
For instance if I have my data : 
```json
{
 "Value" : "a",
 "ValueDictionnary" : 
 {
   "a" : "A is Cool",
   "b" : "B is Hot"
 }
}
```
I'd like to do :
`{{#Data}}{{#Dy}}ValueDictionnary.{{Value}}{{/Dy}}{{/Data}}`
 to get `A is Cool`

But I can only do this as current context is not available in the lambdas : 
`{{#Dy}}Data.ValueDictionnary.{{Data.Value}}{{/Dy}}`

It also makes impossible any array work in lambdas because scope is lost, I'm not even talking about the memory/processing overhead.

### B. The Question

**So what I'm asking, is the StubbleBuilder keeping a trace of current context, or is there a way to access it in the lambdas ? If not can we easily get it done ?** 

Maybe you'll tell me I was doing it all wrong it Nustache ... 

In Mustache.js it was dead simple as one of the Lambda parameter was giving the builder with the current scope. The nustache solution was really hair-pulling.

From Mustache.js readme, this bold function will render text with all current context, lambdas and partials : 
```js
{
  "name": "Tater",
  "bold": function () {
    return function (text, render) {
      return "<b>" + render(text) + "</b>";
    }
  }
}
```
Thanks a lot !

**Comment by Romanx** [comment]
Hi there,

Originally we did pass a render function much like the mustache.js version but after looking at the spec it defines that any values returned from lambdas should be interpolated and rendered based on the current context. 

If you know the string value in your context that is unchanging you could build a string that will then be interpolated. Another option is to use the lambda signature that takes a `dynamic` as the first argument which will be the current context however you won't get any strong typing to help you. The result will still be interpolated.

Hopefully that makes more sense but please feel free to ask more questions and i'll do my best to help.

**Comment by Baccanno** [comment]
Hi Thanks for you answer,

In Nustache the returned string is not interpolated in the context, i.e. `{{something}}`  will render alike.

You're positive that in Stubble this behaviour is changed and the string will be interpolated ?

How would you handle the dynamic thing I'm trying to implement with this way ?

```c#
object MyLambda( dynamic data, string text )
{
 return renderer( "{{{"  + data.RendererWithContext( data.Far.Boo ) + "}}}" );
}
```
Will this work ? However, how do I retrieve the current context from the current renderer as it does not seem retrievable.

```c#
//from StubbleVisitorRenderer, in IStubbleRendere there are only render functions, and they seem to recreate a context from scratch each time. 

renderer.Render(document, new Context(view, RendererSettings, partialsLoader, settings ?? RendererSettings.RenderSettings));
```


If I want to keep it simple do I need to do the following ? It seems the only way to have the string rendered twice with current context. I would have prefered a way to build lambdas with more powerfull capabilities. My template will become really verbose otherwise.

```c#
object Rec( dynamic data, string text )
{
 return text;
}

object Dy( dynamic data, string text )
{
 return "{{{"  + text + "}}}" ;
}
```
`{{#Dy}}{{#Rec}}myVar.{{something}}{{/Rec}}{{/Dy}}`

Best

**Comment by Baccanno** [comment]
I'm trying to achieve exactly the example I've shown. That's why I also cited Mustache.js as here they provide a Render function that will allow rendering in lambdas from context/scope/partials. And it does so without giving access to the context and thus it can't be tampered with.

I'd really like to avoid using a JS parser to use Mustach.js capabilities, adding a 3rd lambda function to the 2 you already handle would do the trick.

**Comment by Baccanno** [comment]
I'd like to be able to do this use case : https://github.com/janl/mustache.js#functions
```
object MyLambda( Func<string, string> renderFunc, string text )
{
 return "{{{"  + renderFunc(text) + "}}}";
}
```

**Comment by Romanx** [comment]
@Baccanno thank you for your help with this. I've decided that adding this overload is not a large amount of work, it won't have too much overhead for others using the library and will unlock migrations for people from `mustache.js`.

I've updated the name of the issue and added this to a milestone. I'll update here when I have more

Thanks,

**Comment by Baccanno** [comment]
I'm very pleased to hear this. In my opinion this what made mustache very powerful when I used it in js projects.

**Comment by Romanx** [comment]
This was just released with 1.3 on Nuget.  Thank you @Baccanno for working through this with me. Hopefully this solves your problem.

**Comment by Baccanno** [comment]
Took some time to get a feedback on this, but it works perfectly well ! Thank you so much.

**Comment by Romanx** [comment]
@Baccanno Good to hear that it works for you!
