### ISSUE TITLE
Feature: Add string formatter extension

### ISSUE THREAD

**Issue by emazv72** [StubbleOrg/Stubble#51]
Would you consider adding a non standard, .net related extension like this one:

https://github.com/emazv72/Stubble.Extensions.StringFormatter

Thank you

**Comment by Romanx** [comment]
Hi there,

This looks like a really useful extension however we probably wouldn't use it in the core library like the other extensions for `System.Data`. 

It may be a good idea however to add a link in the readme for extensions and highlight them for discovery.
