### ISSUE TITLE
Hash sign(#) missing in Stubble/docs/how-to.md?

### ISSUE THREAD

**Issue by hlhielkema** [StubbleOrg/Stubble#60]
The following example code was not working for me (in `Stubble/docs/how-to.md`):
*(I did not copy the code but used it as a example.)*

```
var obj2 = new {
   Bar = "Bar",
   Foo = new Func<string, object>((str) => { return "Foo {{Bar}}"; })
};

stubble.Render("{{Foo}} Hello World {{/Foo}}", obj2); //Outputs: "Foo Bar"
```
I found in `Stubble/test/Stubble.Core.Tests/StaticStubbleTest.cs` that a **#** is required in the start tag ({{#Foo}}).

**Comment by Romanx** [comment]
Thank you very much for raising the issue. It's been fixed now.
