### ISSUE TITLE
Alpha?

### ISSUE THREAD

**Issue by 304NotModified** [StubbleOrg/Stubble#67]
Is this library still considerd alpha? The nuget packages don't have the alpha postfix anymore, but it's in the readme:

![image](https://user-images.githubusercontent.com/5808377/62395100-87737980-b56f-11e9-8dd1-af7f516a6a31.png)

**Comment by Romanx** [comment]
Hey thanks for leaving a comment.

The library is not in alpha, it's just a relic from the past that we need to fix. Thanks for pointing it out

**Comment by Romanx** [comment]
This has now been updated, thanks again for pointing this out
