### ISSUE TITLE
how to render list with comma separated values without trailing comma?

### ISSUE THREAD

**Issue by amithegde** [StubbleOrg/Stubble#77]
I noticed https://github.com/samskivert/jmustache has a feature to print comma separated values without trailing comma using a template like this:

`{{#items}}{{name}}{{^-last}}, {{/-last}}{{/items}}`

what is the recommended approach here?

**Comment by Romanx** [comment]
Hi there,

We deliberately try to implement the mustache standard without any of the extras that other implementations provide.

There are some standard mustache ways of doing this which is usually manipulating your data which you can find [here.](https://stackoverflow.com/questions/6114435/in-mustache-templating-is-there-an-elegant-way-of-expressing-a-comma-separated-l)

You can register your own tag parsers and handlers to add such functionality (and also provide it in an extension package).

Another option is to use our alpha package of helper functions which provide some custom functionality which you can find [here.](https://github.com/StubbleOrg/Stubble.Helpers)

Hope that helps,
