### ISSUE TITLE
ASP.NET MVC view engine

### ISSUE THREAD

**Issue by simonech** [StubbleOrg/Stubble#84]
More a question than an issue: is there an implementation of a ViewEngine for ASP.NET MVC5 or ASP.NET MVC Core?

**Comment by Romanx** [comment]
Hi there,

The closest you will find is the Nustache MVC5 view engine which is another project that I support and the predecessor to Stubble.

It is something I've considered so maybe it is worth adding a issue for it.

**Comment by simonech** [comment]
I’m about to start a project that might require using mustache for net as view engine. I’ve had some experience in the early days of asp.net mvc with view engines. I might give it a go in case.

**Comment by Romanx** [comment]
That sounds great. I'd be happy to link to the project and offer any help I could.

Please feel free to open another issue with any problems you face
