### ISSUE TITLE
how to change syntax ?

### ISSUE THREAD

**Issue by yuzd** [StubbleOrg/Stubble#87]
can i 
 
change

{{  }} 

 to
 
<%=   %>

**Comment by Romanx** [comment]
Hi there,

When configuring your renderer as defined in the getting started guide [here](https://github.com/StubbleOrg/Stubble/blob/master/docs/how-to.md) you can call the method `SetDefaultTags` which takes an object allowing you to define the tags. This would look like this:
```csharp
var stubble = new StubbleBuilder()
  .Configure(settings => {
    settings.SetDefaultTags(new Tags("<%", "%>"));
  })
  .Build();
```

Another option is to use the Set Delimiter tag in your template like this: `{{=<% %>=}}`

Hope that helps,

**Comment by yuzd** [comment]
thanks
